spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:codingmogul
    driver-class-name: org.h2.Driver
    username: codingmogul
    password: codingmogul

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8010